### PR TITLE
Add Docker support with Dockerfile and docker-compose.yml

### PR DESCRIPTION
**Pull request by adityak74**
This PR adds docker setup for the application. 

## Release Notes

* **New Features**
  * Added Docker and Docker Compose support for containerized deployment with simplified setup.

* **Documentation**
  * Updated port references: development URL now on port 3009, production on port 3008.
  * Added Docker installation guide as recommended deployment method.

* **Chores**
  * Added Docker configuration files for consistent environment setup.

### CODE REVIEW

**Comment by viper151** [comment]
@adityak74 does this work for you ? I don't believe it would easily work as the cwd that is defined in the ~/.Claude/projects jsonl filesa is the absolute path for the host. So the docker image needs to have the exact same path available for it to work.

**Comment by adityak74** [comment]
@viper151 - Yeah it does work as I have the root .claude directory mounted inside the docker image [here](https://github.com/siteboon/claudecodeui/pull/40/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R14). 

Screenshot 2025-07-12 at 11 53 34 AM

**Comment by aslaker** [comment]
Popped in here to see if anyone was working on Docker support, and here it is!  Can't wait.  Let me know if you are looking for an outside set of eyes on the implementation.

**Comment by viper151** [comment]
@aslaker  I wasn't able to verify yet if it's working on not. Only thing I'm concerned about is the ability to work on local folders given the project relies on the cwd of the .claude/projects/[project]/session.jsonl files. And that cwd would be usually the host one  while claude code would run inside the container.

Would be great if you could test that. 
@adityak74  can you also check the environment variables you have with the ports? Just curious why do we also offer the ability to change PORT and VITE_PORT given we already allow mapping of the ports

**Comment by ksingh-scogo** [comment]
@adityak74 @viper151  waiting for this PR to get merged . Happy to help with testing once its done. Do tag me once its ready. Thanks

**Comment by viper151** [comment]
@adityak74 
projects.js:187
- Extracts actual project directories from session files
These paths point to host directories that don't exist in the container the way I see it and in 
claude-cli.js:31 the spawned Claude process uses these host paths as working directories
This is not the only dependency though

**Comment by Anima-t3d** [comment]
Not sure if it's related (could be an issue with my setup) but I could not create projects inside claude code UI, says path `/app/[project-name]` does not exist.
image

**Comment by blackmammoth** [comment]
Hey @adityak74, I tried to test this after merging it with main but it's causing the following error:

```bash

 => ERROR [claude-code-ui  6/12] RUN npm ci                                                                                   384.4s
------
 > [claude-code-ui  6/12] RUN npm ci:
7.596 npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
9.627 npm warn deprecated npmlog@6.0.2: This package is no longer supported.
14.51 npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
16.28 npm warn deprecated gauge@4.0.4: This package is no longer supported.
21.65 npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
25.90 npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
33.14 npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
34.15 npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
384.2
384.2 > @siteboon/claude-code-ui@1.20.1 postinstall
384.2 > node scripts/fix-node-pty.js
384.2
384.2 node:internal/modules/cjs/loader:1215
384.2   throw err;
384.2   ^
384.2
384.2 Error: Cannot find module '/app/scripts/fix-node-pty.js'
384.2     at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
384.2     at Module._load (node:internal/modules/cjs/loader:1043:27)
384.2     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
384.2     at node:internal/main/run_main_module:28:49 {
384.2   code: 'MODULE_NOT_FOUND',
384.2   requireStack: []
384.2 }
384.2
384.2 Node.js v20.19.3
384.2 npm error code 1
384.2 npm error path /app
384.2 npm error command failed
384.2 npm error command sh -c node scripts/fix-node-pty.js
384.2 npm error A complete log of this run can be found in: /root/.npm/_logs/2026-02-27T13_38_21_908Z-debug-0.log
------
failed to solve: process "/bin/sh -c npm ci" did not complete successfully: exit code: 1
```

Can you resolve it so that ithe PR can be reviewed?
